//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Imoveis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bairro
    {
        public bairro()
        {
            this.imovel = new HashSet<imovel>();
        }
    
        public int idBairro { get; set; }
        public string nome { get; set; }
        public Nullable<int> idCidade { get; set; }
    
        public virtual cidade cidade { get; set; }
        public virtual ICollection<imovel> imovel { get; set; }
    }
}
