//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Imoveis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class imovel
    {
        public imovel()
        {
            this.imovel_anuncio = new HashSet<imovel_anuncio>();
            this.imovel_atributo = new HashSet<imovel_atributo>();
            this.imovel_imagens = new HashSet<imovel_imagens>();
            this.usuario_lista_imovel = new HashSet<usuario_lista_imovel>();
            this.usuario = new HashSet<usuario>();
        }
    
        public int idImovel { get; set; }
        public string descricao { get; set; }
        public Nullable<System.DateTime> data_inclusao { get; set; }
        public Nullable<System.DateTime> data_exclusao { get; set; }
        public Nullable<float> latitude { get; set; }
        public Nullable<float> longitude { get; set; }
        public Nullable<int> idBairro { get; set; }
        public Nullable<int> num_acessos { get; set; }
        public byte[] imagem { get; set; }
    
        public virtual bairro bairro { get; set; }
        public virtual ICollection<imovel_anuncio> imovel_anuncio { get; set; }
        public virtual ICollection<imovel_atributo> imovel_atributo { get; set; }
        public virtual ICollection<imovel_imagens> imovel_imagens { get; set; }
        public virtual ICollection<usuario_lista_imovel> usuario_lista_imovel { get; set; }
        public virtual ICollection<usuario> usuario { get; set; }
    }
}
