//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Imoveis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class imovel_atributo_tipo
    {
        public imovel_atributo_tipo()
        {
            this.imovel_atributo = new HashSet<imovel_atributo>();
            this.usuario_pesquisa_imovel_atributo_tipo = new HashSet<usuario_pesquisa_imovel_atributo_tipo>();
            this.imovel_tipo = new HashSet<imovel_tipo>();
        }
    
        public string idImovel_Atributo_Tipo { get; set; }
        public string descricao { get; set; }
        public string observacao { get; set; }
        public Nullable<System.DateTime> data_exclusao { get; set; }
        public string idTipo_Dado { get; set; }
    
        public virtual ICollection<imovel_atributo> imovel_atributo { get; set; }
        public virtual tipo_dado tipo_dado { get; set; }
        public virtual ICollection<usuario_pesquisa_imovel_atributo_tipo> usuario_pesquisa_imovel_atributo_tipo { get; set; }
        public virtual ICollection<imovel_tipo> imovel_tipo { get; set; }
    }
}
