//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Imoveis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class imovel_imagens
    {
        public int idImovel_Imagens { get; set; }
        public Nullable<int> idImovel { get; set; }
        public byte[] Imagem { get; set; }
        public string descricao { get; set; }
    
        public virtual imovel imovel { get; set; }
    }
}
