//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Imoveis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mensagem
    {
        public int idMensagem { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public string texto { get; set; }
        public Nullable<int> idUsuarioDestino { get; set; }
        public Nullable<System.DateTime> data_envio { get; set; }
        public Nullable<System.DateTime> data_recebimento { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
