//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Tcc_Imoveis.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class tcc_imoveisEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new tcc_imoveisEntities object using the connection string found in the 'tcc_imoveisEntities' section of the application configuration file.
        /// </summary>
        public tcc_imoveisEntities() : base("name=tcc_imoveisEntities", "tcc_imoveisEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new tcc_imoveisEntities object.
        /// </summary>
        public tcc_imoveisEntities(string connectionString) : base(connectionString, "tcc_imoveisEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new tcc_imoveisEntities object.
        /// </summary>
        public tcc_imoveisEntities(EntityConnection connection) : base(connection, "tcc_imoveisEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<Imovel_Result> ListaImoveis_Todos()
        {
            return base.ExecuteFunction<Imovel_Result>("ListaImoveis_Todos");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<global::System.String> MostraBuscaSalva()
        {
            return base.ExecuteFunction<global::System.String>("MostraBuscaSalva");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public int InserePoligono()
        {
            return base.ExecuteFunction("InserePoligono");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<Imovel_Result> ListaImoveis_Geo()
        {
            return base.ExecuteFunction<Imovel_Result>("ListaImoveis_Geo");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<Imovel_Result> ListaImoveis_Distance()
        {
            return base.ExecuteFunction<Imovel_Result>("ListaImoveis_Distance");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<GetImovel_Result> get_imovel()
        {
            return base.ExecuteFunction<GetImovel_Result>("get_imovel");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<ImovelAtributo_Result> ListaAtributosImovel()
        {
            return base.ExecuteFunction<ImovelAtributo_Result>("ListaAtributosImovel");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<ImovelImagens_Result> ListaImagensImovel()
        {
            return base.ExecuteFunction<ImovelImagens_Result>("ListaImagensImovel");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<Imovel_Result> ListaImoveisValidos()
        {
            return base.ExecuteFunction<Imovel_Result>("ListaImoveisValidos");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<Pesquisa_Result> ListaPesquisaUsuario()
        {
            return base.ExecuteFunction<Pesquisa_Result>("ListaPesquisaUsuario");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<global::System.String> ExibePoligono()
        {
            return base.ExecuteFunction<global::System.String>("ExibePoligono");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<Nullable<global::System.Int32>> InserePesquisa()
        {
            return base.ExecuteFunction<Nullable<global::System.Int32>>("InserePesquisa");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public int InsereAtributoPesquisa()
        {
            return base.ExecuteFunction("InsereAtributoPesquisa");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<AtributosGerais_Result> ListaAtributosGerais()
        {
            return base.ExecuteFunction<AtributosGerais_Result>("ListaAtributosGerais");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<Condicoes_Result> ListaCondicoes()
        {
            return base.ExecuteFunction<Condicoes_Result>("ListaCondicoes");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<TipoDado_Result> ListaTipoDadoCondicoes()
        {
            return base.ExecuteFunction<TipoDado_Result>("ListaTipoDadoCondicoes");
        }

        #endregion
    }
    

    #endregion
    
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="tcc_imoveisModel", Name="AtributosGerais_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class AtributosGerais_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AtributosGerais_Result object.
        /// </summary>
        /// <param name="idImovelAtributoTipo">Initial value of the IdImovelAtributoTipo property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        /// <param name="observacao">Initial value of the Observacao property.</param>
        /// <param name="idTipoDado">Initial value of the IdTipoDado property.</param>
        public static AtributosGerais_Result CreateAtributosGerais_Result(global::System.String idImovelAtributoTipo, global::System.String descricao, global::System.String observacao, global::System.String idTipoDado)
        {
            AtributosGerais_Result atributosGerais_Result = new AtributosGerais_Result();
            atributosGerais_Result.IdImovelAtributoTipo = idImovelAtributoTipo;
            atributosGerais_Result.Descricao = descricao;
            atributosGerais_Result.Observacao = observacao;
            atributosGerais_Result.IdTipoDado = idTipoDado;
            return atributosGerais_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IdImovelAtributoTipo
        {
            get
            {
                return _IdImovelAtributoTipo;
            }
            set
            {
                OnIdImovelAtributoTipoChanging(value);
                ReportPropertyChanging("IdImovelAtributoTipo");
                _IdImovelAtributoTipo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IdImovelAtributoTipo");
                OnIdImovelAtributoTipoChanged();
            }
        }
        private global::System.String _IdImovelAtributoTipo;
        partial void OnIdImovelAtributoTipoChanging(global::System.String value);
        partial void OnIdImovelAtributoTipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Observacao
        {
            get
            {
                return _Observacao;
            }
            set
            {
                OnObservacaoChanging(value);
                ReportPropertyChanging("Observacao");
                _Observacao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Observacao");
                OnObservacaoChanged();
            }
        }
        private global::System.String _Observacao;
        partial void OnObservacaoChanging(global::System.String value);
        partial void OnObservacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IdTipoDado
        {
            get
            {
                return _IdTipoDado;
            }
            set
            {
                OnIdTipoDadoChanging(value);
                ReportPropertyChanging("IdTipoDado");
                _IdTipoDado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IdTipoDado");
                OnIdTipoDadoChanged();
            }
        }
        private global::System.String _IdTipoDado;
        partial void OnIdTipoDadoChanging(global::System.String value);
        partial void OnIdTipoDadoChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="tcc_imoveisModel", Name="Condicoes_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class Condicoes_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Condicoes_Result object.
        /// </summary>
        /// <param name="idCondicao">Initial value of the IdCondicao property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        public static Condicoes_Result CreateCondicoes_Result(global::System.String idCondicao, global::System.String descricao)
        {
            Condicoes_Result condicoes_Result = new Condicoes_Result();
            condicoes_Result.IdCondicao = idCondicao;
            condicoes_Result.Descricao = descricao;
            return condicoes_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IdCondicao
        {
            get
            {
                return _IdCondicao;
            }
            set
            {
                OnIdCondicaoChanging(value);
                ReportPropertyChanging("IdCondicao");
                _IdCondicao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IdCondicao");
                OnIdCondicaoChanged();
            }
        }
        private global::System.String _IdCondicao;
        partial void OnIdCondicaoChanging(global::System.String value);
        partial void OnIdCondicaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="tcc_imoveisModel", Name="GetImovel_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class GetImovel_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GetImovel_Result object.
        /// </summary>
        /// <param name="descricao">Initial value of the descricao property.</param>
        /// <param name="nome">Initial value of the nome property.</param>
        public static GetImovel_Result CreateGetImovel_Result(global::System.String descricao, global::System.String nome)
        {
            GetImovel_Result getImovel_Result = new GetImovel_Result();
            getImovel_Result.descricao = descricao;
            getImovel_Result.nome = nome;
            return getImovel_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descricao
        {
            get
            {
                return _descricao;
            }
            set
            {
                OndescricaoChanging(value);
                ReportPropertyChanging("descricao");
                _descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descricao");
                OndescricaoChanged();
            }
        }
        private global::System.String _descricao;
        partial void OndescricaoChanging(global::System.String value);
        partial void OndescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String x
        {
            get
            {
                return _x;
            }
            set
            {
                OnxChanging(value);
                ReportPropertyChanging("x");
                _x = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("x");
                OnxChanged();
            }
        }
        private global::System.String _x;
        partial void OnxChanging(global::System.String value);
        partial void OnxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String y
        {
            get
            {
                return _y;
            }
            set
            {
                OnyChanging(value);
                ReportPropertyChanging("y");
                _y = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("y");
                OnyChanged();
            }
        }
        private global::System.String _y;
        partial void OnyChanging(global::System.String value);
        partial void OnyChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="tcc_imoveisModel", Name="Imovel_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class Imovel_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Imovel_Result object.
        /// </summary>
        /// <param name="x">Initial value of the x property.</param>
        /// <param name="y">Initial value of the y property.</param>
        /// <param name="bairro">Initial value of the bairro property.</param>
        /// <param name="cidade">Initial value of the cidade property.</param>
        /// <param name="estado">Initial value of the estado property.</param>
        /// <param name="descricao">Initial value of the descricao property.</param>
        /// <param name="idImovel">Initial value of the idImovel property.</param>
        public static Imovel_Result CreateImovel_Result(global::System.String x, global::System.String y, global::System.String bairro, global::System.String cidade, global::System.String estado, global::System.String descricao, global::System.Int32 idImovel)
        {
            Imovel_Result imovel_Result = new Imovel_Result();
            imovel_Result.x = x;
            imovel_Result.y = y;
            imovel_Result.bairro = bairro;
            imovel_Result.cidade = cidade;
            imovel_Result.estado = estado;
            imovel_Result.descricao = descricao;
            imovel_Result.idImovel = idImovel;
            return imovel_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String x
        {
            get
            {
                return _x;
            }
            set
            {
                OnxChanging(value);
                ReportPropertyChanging("x");
                _x = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("x");
                OnxChanged();
            }
        }
        private global::System.String _x;
        partial void OnxChanging(global::System.String value);
        partial void OnxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String y
        {
            get
            {
                return _y;
            }
            set
            {
                OnyChanging(value);
                ReportPropertyChanging("y");
                _y = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("y");
                OnyChanged();
            }
        }
        private global::System.String _y;
        partial void OnyChanging(global::System.String value);
        partial void OnyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String bairro
        {
            get
            {
                return _bairro;
            }
            set
            {
                OnbairroChanging(value);
                ReportPropertyChanging("bairro");
                _bairro = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("bairro");
                OnbairroChanged();
            }
        }
        private global::System.String _bairro;
        partial void OnbairroChanging(global::System.String value);
        partial void OnbairroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cidade
        {
            get
            {
                return _cidade;
            }
            set
            {
                OncidadeChanging(value);
                ReportPropertyChanging("cidade");
                _cidade = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cidade");
                OncidadeChanged();
            }
        }
        private global::System.String _cidade;
        partial void OncidadeChanging(global::System.String value);
        partial void OncidadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.String _estado;
        partial void OnestadoChanging(global::System.String value);
        partial void OnestadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descricao
        {
            get
            {
                return _descricao;
            }
            set
            {
                OndescricaoChanging(value);
                ReportPropertyChanging("descricao");
                _descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descricao");
                OndescricaoChanged();
            }
        }
        private global::System.String _descricao;
        partial void OndescricaoChanging(global::System.String value);
        partial void OndescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imagem
        {
            get
            {
                return _imagem;
            }
            set
            {
                OnimagemChanging(value);
                ReportPropertyChanging("imagem");
                _imagem = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("imagem");
                OnimagemChanged();
            }
        }
        private global::System.String _imagem;
        partial void OnimagemChanging(global::System.String value);
        partial void OnimagemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idImovel
        {
            get
            {
                return _idImovel;
            }
            set
            {
                OnidImovelChanging(value);
                ReportPropertyChanging("idImovel");
                _idImovel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idImovel");
                OnidImovelChanged();
            }
        }
        private global::System.Int32 _idImovel;
        partial void OnidImovelChanging(global::System.Int32 value);
        partial void OnidImovelChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="tcc_imoveisModel", Name="ImovelAtributo_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class ImovelAtributo_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ImovelAtributo_Result object.
        /// </summary>
        /// <param name="valor">Initial value of the valor property.</param>
        /// <param name="descricao">Initial value of the descricao property.</param>
        public static ImovelAtributo_Result CreateImovelAtributo_Result(global::System.String valor, global::System.String descricao)
        {
            ImovelAtributo_Result imovelAtributo_Result = new ImovelAtributo_Result();
            imovelAtributo_Result.valor = valor;
            imovelAtributo_Result.descricao = descricao;
            return imovelAtributo_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String valor
        {
            get
            {
                return _valor;
            }
            set
            {
                OnvalorChanging(value);
                ReportPropertyChanging("valor");
                _valor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("valor");
                OnvalorChanged();
            }
        }
        private global::System.String _valor;
        partial void OnvalorChanging(global::System.String value);
        partial void OnvalorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descricao
        {
            get
            {
                return _descricao;
            }
            set
            {
                OndescricaoChanging(value);
                ReportPropertyChanging("descricao");
                _descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descricao");
                OndescricaoChanged();
            }
        }
        private global::System.String _descricao;
        partial void OndescricaoChanging(global::System.String value);
        partial void OndescricaoChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="tcc_imoveisModel", Name="ImovelGeo_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class ImovelGeo_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ImovelGeo_Result object.
        /// </summary>
        /// <param name="idImovel">Initial value of the idImovel property.</param>
        /// <param name="x">Initial value of the x property.</param>
        /// <param name="y">Initial value of the y property.</param>
        public static ImovelGeo_Result CreateImovelGeo_Result(global::System.Int32 idImovel, global::System.Decimal x, global::System.Decimal y)
        {
            ImovelGeo_Result imovelGeo_Result = new ImovelGeo_Result();
            imovelGeo_Result.idImovel = idImovel;
            imovelGeo_Result.x = x;
            imovelGeo_Result.y = y;
            return imovelGeo_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idImovel
        {
            get
            {
                return _idImovel;
            }
            set
            {
                OnidImovelChanging(value);
                ReportPropertyChanging("idImovel");
                _idImovel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idImovel");
                OnidImovelChanged();
            }
        }
        private global::System.Int32 _idImovel;
        partial void OnidImovelChanging(global::System.Int32 value);
        partial void OnidImovelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal x
        {
            get
            {
                return _x;
            }
            set
            {
                OnxChanging(value);
                ReportPropertyChanging("x");
                _x = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("x");
                OnxChanged();
            }
        }
        private global::System.Decimal _x;
        partial void OnxChanging(global::System.Decimal value);
        partial void OnxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal y
        {
            get
            {
                return _y;
            }
            set
            {
                OnyChanging(value);
                ReportPropertyChanging("y");
                _y = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("y");
                OnyChanged();
            }
        }
        private global::System.Decimal _y;
        partial void OnyChanging(global::System.Decimal value);
        partial void OnyChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="tcc_imoveisModel", Name="ImovelImagens_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class ImovelImagens_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ImovelImagens_Result object.
        /// </summary>
        /// <param name="imagem">Initial value of the imagem property.</param>
        /// <param name="descricao">Initial value of the descricao property.</param>
        public static ImovelImagens_Result CreateImovelImagens_Result(global::System.String imagem, global::System.String descricao)
        {
            ImovelImagens_Result imovelImagens_Result = new ImovelImagens_Result();
            imovelImagens_Result.imagem = imagem;
            imovelImagens_Result.descricao = descricao;
            return imovelImagens_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String imagem
        {
            get
            {
                return _imagem;
            }
            set
            {
                OnimagemChanging(value);
                ReportPropertyChanging("imagem");
                _imagem = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("imagem");
                OnimagemChanged();
            }
        }
        private global::System.String _imagem;
        partial void OnimagemChanging(global::System.String value);
        partial void OnimagemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descricao
        {
            get
            {
                return _descricao;
            }
            set
            {
                OndescricaoChanging(value);
                ReportPropertyChanging("descricao");
                _descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descricao");
                OndescricaoChanged();
            }
        }
        private global::System.String _descricao;
        partial void OndescricaoChanging(global::System.String value);
        partial void OndescricaoChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="tcc_imoveisModel", Name="Pesquisa_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class Pesquisa_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pesquisa_Result object.
        /// </summary>
        /// <param name="nome">Initial value of the nome property.</param>
        /// <param name="idPesquisa">Initial value of the idPesquisa property.</param>
        public static Pesquisa_Result CreatePesquisa_Result(global::System.String nome, global::System.Int32 idPesquisa)
        {
            Pesquisa_Result pesquisa_Result = new Pesquisa_Result();
            pesquisa_Result.nome = nome;
            pesquisa_Result.idPesquisa = idPesquisa;
            return pesquisa_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idPesquisa
        {
            get
            {
                return _idPesquisa;
            }
            set
            {
                OnidPesquisaChanging(value);
                ReportPropertyChanging("idPesquisa");
                _idPesquisa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idPesquisa");
                OnidPesquisaChanged();
            }
        }
        private global::System.Int32 _idPesquisa;
        partial void OnidPesquisaChanging(global::System.Int32 value);
        partial void OnidPesquisaChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="tcc_imoveisModel", Name="TipoDado_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class TipoDado_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TipoDado_Result object.
        /// </summary>
        /// <param name="idtipo_dado">Initial value of the idtipo_dado property.</param>
        public static TipoDado_Result CreateTipoDado_Result(global::System.String idtipo_dado)
        {
            TipoDado_Result tipoDado_Result = new TipoDado_Result();
            tipoDado_Result.idtipo_dado = idtipo_dado;
            return tipoDado_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String idpesquisa_condicoes
        {
            get
            {
                return _idpesquisa_condicoes;
            }
            set
            {
                Onidpesquisa_condicoesChanging(value);
                ReportPropertyChanging("idpesquisa_condicoes");
                _idpesquisa_condicoes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("idpesquisa_condicoes");
                Onidpesquisa_condicoesChanged();
            }
        }
        private global::System.String _idpesquisa_condicoes;
        partial void Onidpesquisa_condicoesChanging(global::System.String value);
        partial void Onidpesquisa_condicoesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String idtipo_dado
        {
            get
            {
                return _idtipo_dado;
            }
            set
            {
                Onidtipo_dadoChanging(value);
                ReportPropertyChanging("idtipo_dado");
                _idtipo_dado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("idtipo_dado");
                Onidtipo_dadoChanged();
            }
        }
        private global::System.String _idtipo_dado;
        partial void Onidtipo_dadoChanging(global::System.String value);
        partial void Onidtipo_dadoChanged();

        #endregion
    }

    #endregion
    
}
