//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Imoveis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pesquisa_condicoes
    {
        public pesquisa_condicoes()
        {
            this.usuario_pesquisa_imovel_atributo_tipo = new HashSet<usuario_pesquisa_imovel_atributo_tipo>();
        }
    
        public string idPesquisa_Condicoes { get; set; }
        public string descricao { get; set; }
    
        public virtual ICollection<usuario_pesquisa_imovel_atributo_tipo> usuario_pesquisa_imovel_atributo_tipo { get; set; }
    }
}
