//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Imoveis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_dado
    {
        public tipo_dado()
        {
            this.imovel_atributo_tipo = new HashSet<imovel_atributo_tipo>();
        }
    
        public string idTipo_Dado { get; set; }
        public string nome { get; set; }
    
        public virtual ICollection<imovel_atributo_tipo> imovel_atributo_tipo { get; set; }
    }
}
