//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Imoveis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uf
    {
        public uf()
        {
            this.cidade = new HashSet<cidade>();
        }
    
        public string idUF { get; set; }
        public string descricao { get; set; }
    
        public virtual ICollection<cidade> cidade { get; set; }
    }
}
