//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Imoveis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_pesquisa_imovel_atributo_tipo
    {
        public int idUsuario_Pesquisa_Imovel_Atributo_Tipo { get; set; }
        public Nullable<int> idUsuario_Pesquisa { get; set; }
        public string idImovel_Atributo_Tipo { get; set; }
        public string idCondicao { get; set; }
        public string valor { get; set; }
        public Nullable<int> prioridade { get; set; }
    
        public virtual imovel_atributo_tipo imovel_atributo_tipo { get; set; }
        public virtual pesquisa_condicoes pesquisa_condicoes { get; set; }
        public virtual usuario_pesquisa usuario_pesquisa { get; set; }
    }
}
