//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Imoveis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.mensagem = new HashSet<mensagem>();
            this.mensagem1 = new HashSet<mensagem>();
            this.usuario_lista = new HashSet<usuario_lista>();
            this.usuario_pesquisa = new HashSet<usuario_pesquisa>();
            this.usuario1 = new HashSet<usuario>();
            this.usuario2 = new HashSet<usuario>();
            this.imovel = new HashSet<imovel>();
        }
    
        public int idUsuario { get; set; }
        public string email { get; set; }
        public string senha { get; set; }
        public string nome { get; set; }
        public string idTipo_Usuario { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<mensagem> mensagem { get; set; }
        public virtual ICollection<mensagem> mensagem1 { get; set; }
        public virtual tipo_usuario tipo_usuario { get; set; }
        public virtual ICollection<usuario_lista> usuario_lista { get; set; }
        public virtual ICollection<usuario_pesquisa> usuario_pesquisa { get; set; }
        public virtual ICollection<usuario> usuario1 { get; set; }
        public virtual ICollection<usuario> usuario2 { get; set; }
        public virtual ICollection<imovel> imovel { get; set; }
    }
}
