//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Imoveis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_lista
    {
        public usuario_lista()
        {
            this.usuario_lista_imovel = new HashSet<usuario_lista_imovel>();
        }
    
        public int idUsuario_Lista { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public string nome { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual ICollection<usuario_lista_imovel> usuario_lista_imovel { get; set; }
    }
}
