//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Imoveis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_pesquisa
    {
        public usuario_pesquisa()
        {
            this.usuario_pesquisa_imovel_atributo_tipo = new HashSet<usuario_pesquisa_imovel_atributo_tipo>();
            this.usuario_pesquisa_posicao = new HashSet<usuario_pesquisa_posicao>();
        }
    
        public int idUsuario_Pesquisa { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public string nome { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual ICollection<usuario_pesquisa_imovel_atributo_tipo> usuario_pesquisa_imovel_atributo_tipo { get; set; }
        public virtual ICollection<usuario_pesquisa_posicao> usuario_pesquisa_posicao { get; set; }
    }
}
