//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Imoveis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_pesquisa_usuario_tipos_atributos_imovel
    {
        public int idUsuario_Pesquisa { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public string nome { get; set; }
        public int idUsuario_Pesquisa_Imovel_Atributo_Tipo { get; set; }
        public string idImovel_Atributo_Tipo { get; set; }
        public string idCondicao { get; set; }
        public string valor { get; set; }
        public Nullable<int> prioridade { get; set; }
    }
}
