//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Imoveis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_imoveis_atendem_tipo_atributo_pesquisa
    {
        public int idImovel_atributo { get; set; }
        public Nullable<int> idImovel { get; set; }
        public string idImovel_Atributo_tipo { get; set; }
        public string valor { get; set; }
        public Nullable<int> Prioridade { get; set; }
        public string idCondicao { get; set; }
        public string valor_pesquisado { get; set; }
        public Nullable<int> prioridade_pesquisado { get; set; }
    }
}
