//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Imoveis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_imoveis_atendem_pelo_menos_uma_condicao_pesquisa
    {
        public Nullable<int> idUsuario { get; set; }
        public string nome { get; set; }
        public int idusuario_Pesquisa { get; set; }
        public int idImovel { get; set; }
    }
}
