//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Imoveis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_imoveis_seus_tipos_atributos
    {
        public int idImovel { get; set; }
        public string descricao { get; set; }
        public Nullable<System.DateTime> data_inclusao { get; set; }
        public Nullable<System.DateTime> data_exclusao { get; set; }
        public Nullable<float> latitude { get; set; }
        public Nullable<float> longitude { get; set; }
        public Nullable<int> idBairro { get; set; }
        public Nullable<int> num_acessos { get; set; }
        public byte[] imagem { get; set; }
        public int idImovel_Atributo { get; set; }
        public string idImovel_Atributo_Tipo { get; set; }
        public string valor { get; set; }
        public Nullable<int> prioridade { get; set; }
    }
}
